spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create                          # create(??? ??? ?? ??), update(?? ???? ??), none()
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    # ???? ?? ?, ??? ??? ???? ???
      use-new-id-generator-mappings: false       # JPA? ???? ?? ??? ??? ???? ???. -> DB? ??? ??? ???
    show-sql: true
    properties:
      hibernate:
        format_sql: true
